### ISSUE TITLE
Desktop main drawer menu

### ISSUE THREAD

**Issue by netpoe** [aufacicenta/pancakeswap-clone#6]
## Acceptance Critera — AC

- [ ] I can see the main menu items in the sidebar drawer menu
- [ ] I can click on the main menu links and be redirected to the corresponding page
- [ ] I can collapse the drawer with the hamburger menu icon in the header
